# fish completions for harrow. Generated by `harrow completions fish`.
#
# Install:  harrow completions fish > ~/.config/fish/completions/harrow.fish

# No files unless a flag asks for one: harrow takes no positional
# arguments, so offering the working directory is noise.
complete -c harrow -f

complete -c harrow -n __fish_use_subcommand -a config -d 'show the configuration in effect, or write a commented default'
complete -c harrow -n __fish_use_subcommand -a themes -d 'list every theme harrow can find'
complete -c harrow -n __fish_use_subcommand -a completions -d 'print a completion script for fish, bash or zsh'
complete -c harrow -n __fish_use_subcommand -a man -d 'print the man page'

complete -c harrow -n '__fish_seen_subcommand_from completions' -a 'fish bash zsh' -d 'shell'
complete -c harrow -n '__fish_seen_subcommand_from config' -l write -d 'write a commented default'
complete -c harrow -n '__fish_seen_subcommand_from config' -l force -d 'replace an existing file'

complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s C -l directory -x -a '(__fish_complete_directories)' -d 'start looking for the project here'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s a -l all -d 'show everything: finished, dropped, milestones'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s b -l board -d 'open on the board'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l stats -d 'open on the statistics'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s f -l filter -x -d 'open filtered, in cairn\'s grammar'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l view -x -d 'open in one of the project\'s saved views'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l group-by -x -d 'milestone, status, type, or any field'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l sort -x -d 'sort keys, `-` for descending'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s p -l plain -d 'print one line per item and exit'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l theme -x -a '(harrow themes 2>/dev/null | string trim | string split -f1 " ")' -d 'use a theme for this run (auto, mono, gotham, …)'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l config -r -F -d 'read this config file instead of the usual one'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l color -x -a 'auto always never' -d 'always, never, or auto'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l no-color -d 'same as --color never'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l doctor -d 'check everything harrow depends on'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l screenshot -x -d 'render one frame as text and exit'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -l fix-terminal -d 'undo a terminal left in mouse-reporting mode'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s h -l help -d 'show this help'
complete -c harrow -n 'not __fish_seen_subcommand_from config themes completions' -s V -l version -d 'show the version'
